### ISSUE TITLE
GitHub Authentication issue

### ISSUE THREAD

**Issue by nakoeppen** [LillyWho/pihole-FTL-openrc#1]
"The unauthenticated git protocol on port 9418 is no longer supported" when cloning from AUR. Presumably an issue from this repository.

See link: https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git

**Comment by LillyWho** [comment]
If anything, it happens in the package script and has nothing to do with this repo itself. I don't have an Artix Arch setup anymore, so I can't investigate right now.
